# Pandas Data Cleaning Project

In [51]:
import pandas as pd
df = pd.read_excel(r"D:\Private\555 sha\P\pandas-data-cleaning-project\data\raw_data.xlsx")

# 🟢 LEVEL 1 — Basic Structural Cleaning
# Task 1 — Inspect the dataset

**Find : number of rows & number of columns**

In [52]:
df.shape

(500, 11)

**Find : column names**

In [53]:
df.columns

Index([' Employee ID ', 'NAME', 'Department', 'Age', 'Salary', 'Bonus',
       'Join Date', 'Email', 'Phone', 'Gender', 'Status'],
      dtype='str')

**Find : data types**

In [54]:
df.dtypes

 Employee ID        str
NAME                str
Department          str
Age              object
Salary           object
Bonus            object
Join Date        object
Email               str
Phone            object
Gender              str
Status              str
dtype: object

**Find : memory usage**

In [55]:
df.info(memory_usage="deep")

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0    Employee ID   500 non-null    str
 1   NAME           500 non-null    str
 2   Department     499 non-null    str
 3   Age            438 non-null    object
 4   Salary         434 non-null    object
 5   Bonus          403 non-null    object
 6   Join Date      482 non-null    object
 7   Email          488 non-null    str
 8   Phone          484 non-null    object
 9   Gender         427 non-null    str
 10  Status         443 non-null    str
dtypes: object(5), str(6)
memory usage: 276.5 KB

**Find : First 5 rows**

In [56]:
df.head(5)

,Employee ID,NAME,Department,Age,Salary,Bonus,Join Date,Email,Phone,Gender,Status
0,E001,John Smith,IT,25,5000,500,unknown,noor.martin@hotmail.com,97474793157,M,NaN
1,E002,MARY JOHNSON,it,30,6000,NaN,2020-07-09 00:00:00,joseph.yusuf@gmail.com,+974 7824 2882,f,Active
2,E003,ahmed ali,IT Department,35,7500.5,?,2020-03-19 00:00:00,mary.brown@yahoo.com,37773911,Female,A
3,E004,Sara Khan,HR,NaN,NaN,500,2024-12-02 00:00:00,daniel.johnson@yahoo.com,37855874,Female,Inactive
4,E005,Robert Brown,Human Resources,42,8000,Unknown,18-05-2024,ali.thomas@hotmail.com,+974 5995 1676,Male,active

**Find : Last 5 rows**

In [57]:
df.tail(5)

,Employee ID,NAME,Department,Age,Salary,Bonus,Join Date,Email,Phone,Gender,Status
495,E496,Daniel Smith,Sales,45,unknown,-50,2019-02-09 00:00:00,emma.taylor@company.com,31753140,Female,ACTIVE
496,E497,Maya Ali,IT Department,32,4800,1000,2020-02-18,ryan.taylor@hotmail.com,974-5587-2645,m,ACTIVE
497,E498,Unknown,Marketing,27,NaN,300,2020-12-15 00:00:00,amira.moore@gmail.com,974-6740-1535,female,Inactive
498,E500,Peter Khan,HR,-8,7000,not available,December 15 2019,joseph.brown@hotmail.com,-9530,M,unknown
499,E500,Hana Davis,Operations,38,6200,NaN,16-10-2023,john..smith@gmail.com,974-7468-5012,male,INACTIVE